/**
 * Gera 4 arquivos .md em public/ a partir dos dados canônicos em src/data/.
 * Expõe markdown cru para LLMs (Anthropic, OpenAI, Perplexity etc.) consumirem
 * sem o ruído HTML das páginas. Indexado também pelo llms.txt.
 *
 * Executado antes de `astro build` (ver package.json).
 *  - public/faq.md       → src/data/faqs.ts
 *  - public/glossario.md → src/data/glossario.ts
 *  - public/servicos.md  → src/data/servicos.ts
 *  - public/materiais.md → catálogo inline (alinhar manualmente quando mudar materiais)
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { faqs } from '../src/data/faqs.js'
import { terms } from '../src/data/glossario.js'
import { services, processSteps } from '../src/data/servicos.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PUBLIC = resolve(__dirname, '..', 'public')
mkdirSync(PUBLIC, { recursive: true })

const SITE = 'https://aumaf.kayoridolfi.ai'
const NOW = new Date().toISOString().slice(0, 10)
const HEADER = (title: string, subtitle: string) => `<!-- Generated by scripts/generate-llm-sources.ts on ${NOW} — do not edit by hand. -->
# ${title}

> ${subtitle}
>
> Fonte canônica para LLMs e crawlers. HTML correspondente em ${SITE}.

`

// ── FAQ ──────────────────────────────────────────────────────────────────
{
  let md = HEADER(
    'FAQ AUMAF 3D — Manufatura Aditiva',
    `Perguntas frequentes sobre impressão 3D industrial em São Carlos – SP. ${faqs.reduce((n, g) => n + g.items.length, 0)} perguntas em ${faqs.length} categorias.`,
  )
  for (const g of faqs) {
    md += `## ${g.cat}\n\n`
    for (const it of g.items) {
      md += `### ${it.q}\n\n${it.a}\n\n`
    }
  }
  md += `---\n\nVer também: ${SITE}/faq · ${SITE}/glossario · ${SITE}/servicos · ${SITE}/materiais\n`
  writeFileSync(resolve(PUBLIC, 'faq.md'), md)
}

// ── Glossário ────────────────────────────────────────────────────────────
{
  let md = HEADER(
    'Glossário técnico de manufatura aditiva — AUMAF 3D',
    `${terms.length} termos essenciais de impressão 3D — processos, materiais, conceitos de design e formatos de arquivo.`,
  )
  for (const t of terms) {
    md += `### ${t.term}\n\n${t.definition}\n\n`
  }
  md += `---\n\nVer também: ${SITE}/glossario · ${SITE}/materiais · ${SITE}/faq\n`
  writeFileSync(resolve(PUBLIC, 'glossario.md'), md)
}

// ── Serviços ─────────────────────────────────────────────────────────────
{
  let md = HEADER(
    'Serviços AUMAF 3D — Impressão 3D Industrial',
    'Quatro serviços integrados: prototipagem, peças funcionais & metal, modelagem 3D/DfAM, engenharia reversa.',
  )
  for (const s of services) {
    md += `## ${s.num} · ${s.title}\n\n${s.body}\n\n`
    md += `**Especificações**: ${s.specs.join(' · ')}\n\n`
    md += '**Detalhes**\n'
    for (const d of s.details) {
      md += `- ${d.label}: ${d.value}\n`
    }
    md += `\nURL: ${SITE}/servicos#${s.id}\n\n`
  }
  md += `## Como funciona — passo a passo\n\n`
  for (const step of processSteps) {
    md += `${step.n}. **${step.title}** — ${step.body}\n`
  }
  md += `\n---\n\nOrçamento em 24h: ${SITE}/contato · WhatsApp (16) 99286-3412.\n`
  writeFileSync(resolve(PUBLIC, 'servicos.md'), md)
}

// ── Materiais ────────────────────────────────────────────────────────────
// Catálogo compacto (não-paramétrico) — fonte de UI rica está em src/pages/materiais.astro.
// Atualizar manualmente quando adicionar/remover material; estável o suficiente para LLMs.
{
  const lista: Array<{ name: string; process: string; tempMax: string; app: string; bullet: string }> = [
    { name: 'PLA',                  process: 'FDM', tempMax: '60°C',   app: 'Protótipos visuais e maquetes',           bullet: 'Biodegradável, fácil de imprimir, baixa resistência térmica.' },
    { name: 'Nylon (PA)',           process: 'FDM', tempMax: '120°C',  app: 'Engrenagens, buchas, peças com atrito',   bullet: 'Tenaz e resistente ao desgaste; absorve umidade.' },
    { name: 'ABS',                  process: 'FDM', tempMax: '100°C',  app: 'Protótipos funcionais e carcaças',        bullet: 'Pós-processo por acetona; requer câmara fechada.' },
    { name: 'ASA',                  process: 'FDM', tempMax: '100°C',  app: 'Peças expostas ao sol e à chuva',         bullet: 'Resistência UV superior ao ABS.' },
    { name: 'Policarbonato (PC)',   process: 'FDM', tempMax: '130°C',  app: 'Componentes sob impacto e calor',         bullet: 'Maior resistência ao impacto entre termoplásticos comuns.' },
    { name: 'PET-G',                process: 'FDM', tempMax: '80°C',   app: 'Embalagens, peças translúcidas',          bullet: 'Tenaz, FDA grade disponível.' },
    { name: 'Polipropileno (PP)',   process: 'FDM', tempMax: '100°C',  app: 'Recipientes químicos, living hinges',     bullet: 'Excelente resistência química e fadiga em flexão.' },
    { name: 'TPU',                  process: 'FDM', tempMax: '80°C',   app: 'Solas, vedações, cases protetores',       bullet: 'Elastômero Shore A 85–95.' },
    { name: 'PVA',                  process: 'FDM', tempMax: '60°C',   app: 'Suporte solúvel em água',                 bullet: 'Para geometrias internas complexas em dual-extrusion.' },
    { name: 'PA CF15',              process: 'FDM', tempMax: '180°C',  app: 'Substituição de metal em drones/SAE',     bullet: 'Nylon + 15% fibra de carbono; rigidez excepcional.' },
    { name: 'PET-G CF15',           process: 'FDM', tempMax: '80°C',   app: 'Estruturas leves premium',                bullet: 'PET-G reforçado, acabamento fosco.' },
    { name: 'Tritan HT',            process: 'FDM', tempMax: '95°C',   app: 'Peças visíveis transparentes (alimento)', bullet: 'Copoliéster Eastman, BPA-free.' },
    { name: 'PC industrial',        process: 'FDM', tempMax: '130°C',  app: 'EPI estrutural, capacetes',               bullet: 'Variante industrial do Policarbonato.' },
    { name: 'TPU Shore 95A',        process: 'FDM', tempMax: '80°C',   app: 'Juntas, vedações dinâmicas',              bullet: 'Flex médio com retenção de forma.' },
    { name: 'Flex Shore 85A',       process: 'FDM', tempMax: '70°C',   app: 'Solas, grips, amortecedores',             bullet: 'Tato de borracha macia.' },
    { name: 'Resina Standard',      process: 'SLA', tempMax: '60°C',   app: 'Miniaturas, joalheria, alto detalhe',     bullet: 'Camada 25–100 µm, acabamento liso.' },
    { name: 'Resina ABS-Like',      process: 'SLA', tempMax: '80°C',   app: 'Peças funcionais detalhadas',             bullet: 'Mecânica + detalhe SLA.' },
    { name: 'Nylon PA12 (pó)',      process: 'SLS', tempMax: '170°C',  app: 'Peças funcionais sem suporte',            bullet: 'Geometrias internas livres, lattice, séries piloto.' },
    { name: 'Aço Inox 316L',        process: 'SLM', tempMax: '800°C+', app: 'Peças metálicas finais (alimentar/marítimo)', bullet: 'Densidade >99%, padrão ASTM 316L.' },
  ]
  let md = HEADER(
    'Catálogo de materiais — AUMAF 3D',
    `${lista.length} materiais disponíveis por processo (FDM, SLA, SLS, SLM). Especificações completas em ${SITE}/materiais.`,
  )
  md += `## Materiais por processo\n\n`
  md += `| Material | Processo | Temp. máx. | Aplicação | Resumo |\n|---|---|---|---|---|\n`
  for (const m of lista) {
    md += `| ${m.name} | ${m.process} | ${m.tempMax} | ${m.app} | ${m.bullet} |\n`
  }
  md += `\n## Capacidade de impressão\n\n`
  md += `- FDM: 600 × 600 × 600 mm em peça única\n`
  md += `- SLA: 600 × 600 × 400 mm\n`
  md += `- SLS: 400 × 400 × 420 mm\n`
  md += `- SLM (metal): 470 × 270 × 300 mm\n\n`
  md += `---\n\nVer também: ${SITE}/materiais · ${SITE}/glossario · ${SITE}/servicos\n`
  writeFileSync(resolve(PUBLIC, 'materiais.md'), md)
}

console.log('[llm-sources] wrote faq.md, glossario.md, servicos.md, materiais.md to public/')
